name: "Assign author review"
description: "Automatically assign git commit authors as review on release PRs"
inputs:
  token:
    description: "The token that the action will use to assign reviewers"
    required: true
    default: ${{ github.token }}
# outputs:
#   time: # id of output
#     description: "The time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
