name: Assign reviewers to release PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - "stage"
      - "prod"

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    name: Assign reviewers
    steps:
      - name: Assign reviewers
        uses: understory-io/assign-reviewers-github-action@main
