name: Update release PRs
on:
  push:
    branches:
      - "dev"
      - "stage"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-prs:
    uses: understory-io/workflows/.github/workflows/create-deployment-prs.yml@feature/release-prs
    secrets:
      token: ${{ secrets.PAT }}
