name: Automatically create / update release PRs

on:
  push:
    branches:
      - "dev"
      - "stage"

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set target branch
        id: set-target-branch
        run: echo "TARGET_BRANCH=$([[ '${{ github.ref_name }}' == 'dev' ]] && echo 'stage' || ([[ '${{ github.ref_name }}' == 'stage' ]] && echo 'prod' || echo 'unknown'))" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            Merge ${{ github.ref_name }} into ${{ steps.set-target-branch.outputs.TARGET_BRANCH }}
          branch: ${{ steps.set-target-branch.outputs.TARGET_BRANCH }}
          title:
            "Release ${{ github.ref_name }} to ${{ steps.set-target-branch.outputs.TARGET_BRANCH }}"
            # consider having tags in here to ping commit authors
          body: "Automated PR for releasing changes from ${{ github.ref_name }} into ${{ steps.set-target-branch.outputs.TARGET_BRANCH }}"
          maintainer-can-modify: false
